version: '3.3'

services:
  db:
    container_name: db
    image: "mysql:latest"
    restart: always
    networks:
      - default
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=database
      - MYSQL_ROOT_PASSWORD=password
    

  app:
    container_name: app
    build: .
    ports:
      - "8080:8080"
    networks:
      - default
    expose: 
    - 8080
    depends_on:
      - db
    environment:
      - DBUSER=root
      - DBPASS=password
      - DBNAME=database
      - DBHOST=db
      - DBPORT=3306

  